[package]
name = "automerge-persistent"
version = "0.1.0"
authors = ["Andrew Jeffery <dev@jeffas.io>"]
edition = "2018"

[dependencies]
automerge = { git = "https://github.com/jeromegn/automerge-rs", branch = "experiment-observer" }
thiserror = "1.0.24"
